const {
  KINGSTINCT_BULL_REDIS_URL,
  KINGSTINCT_PUSHOVER_DEVICE,
  KINGSTINCT_PUSHOVER_PRIORITY,
  KINGSTINCT_PUSHOVER_SOUND,
  KINGSTINCT_PUSHOVER_TITLE,
  KINGSTINCT_PUSHOVER_TOKEN,
  KINGSTINCT_PUSHOVER_URL_TITLE,
  KINGSTINCT_PUSHOVER_URL,
  KINGSTINCT_PUSHOVER_USER,
} = process.env;

export {
  KINGSTINCT_BULL_REDIS_URL,
  KINGSTINCT_PUSHOVER_DEVICE,
  KINGSTINCT_PUSHOVER_PRIORITY,
  KINGSTINCT_PUSHOVER_SOUND,
  KINGSTINCT_PUSHOVER_TITLE,
  KINGSTINCT_PUSHOVER_TOKEN,
  KINGSTINCT_PUSHOVER_URL_TITLE,
  KINGSTINCT_PUSHOVER_URL,
  KINGSTINCT_PUSHOVER_USER,
};

export default {
  KINGSTINCT_BULL_REDIS_URL,
  KINGSTINCT_PUSHOVER_DEVICE,
  KINGSTINCT_PUSHOVER_PRIORITY,
  KINGSTINCT_PUSHOVER_SOUND,
  KINGSTINCT_PUSHOVER_TITLE,
  KINGSTINCT_PUSHOVER_TOKEN,
  KINGSTINCT_PUSHOVER_URL_TITLE,
  KINGSTINCT_PUSHOVER_URL,
  KINGSTINCT_PUSHOVER_USER,
};
